### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by anushkaparadkar** [anushkaparadkar/pocket-kampus#1]
## Using the Agile Methodology
- [ ] Plan project in stages and modules
- [ ] Set timelines
- [ ] Assign work
- [ ] Learn the GitHub project system
- [ ] Use different branches for different modules

## Process to be followed:
> Create Issue > Create Branch > Make Commits > Create Pull Request > Wait for Review > Merge
